### ISSUE TITLE
Loss函数是否没有提供？

### ISSUE THREAD

**Issue by ZeHuangFang** [ChangLee0903/SERIL#1]
你好，你们所做的工作很棒！我也很感兴趣~论文中描述的loss函数有点复杂，所以想看一下你们是怎么实现的，不过没有找到，请问是否没有上传loss函数呢？

**Comment by ZeHuangFang** [comment]
不好意思，理解有误，原来是对loss做正则化策略；

**Comment by ChangLee0903** [comment]
謝謝你的欣賞，請問對「損失含數值做正規化策略」是指什麼意思呢？如果是指如何決定正規項權重的部分，我寫在 regularizer.py 裡面，如果是指如何計算正規項，當下在訓練的時候的正規項來自之前得出來的權重乘上當下參數與過去參數距離的總和，這部分寫在 regularizer.py 的 LifeLongAgent class 的 forward。

**Comment by ZeHuangFang** [comment]
Get it! 感谢解答！
是的，我关心的是如何计算以及实现的过程。
